### ISSUE TITLE
백엔드 이찬형 8주차 과제 제출합니다.

### ISSUE THREAD

**Issue by chanbro0524** [likelion-Inha-12/chanbro524#10]
1.URL v.s. Origin v.s. Domain 각각의 개념은 무엇이고, 세 키워드 간의 관계는 어떻게 될까요?
-url:URL은 웹 리소스의 위치를 지정하는 문자열입니다. URL은 웹 페이지, 이미지, 동영상 등과 같은 웹 상의 모든 리소스를 가리킬 수 있습니다. 
-origin:Origin은 웹 리소스의 출처를 정의하는 세 가지 요소의 조합입니다:
-domain:Domain은 웹 사이트의 주소를 나타내는 부분으로, 보통 사용자가 기억하기 쉽도록 설계됩니다. 도메인은 여러 수준으로 구성될 수 있습니다:
URL은 Origin과 Domain을 포함하는 더 포괄적인 개념입니다. URL은 리소스의 전체 경로를 제공하는 반면, Origin은 보안상의 이유로 프로토콜, 도메인, 포트 번호의 조합만을 나타냅니다.
Domain은 URL과 Origin의 일부입니다. URL과 Origin 둘 다 도메인 이름을 포함하지만, URL은 더 구체적이고 Origin은 보안과 출처 확인에 초점을 맞춥니다.

2.https://lionz12.netlify.app과 아래의 URL을 비교하여 같은 출처인지, 다른 출처인지 그리고 그 이유는 무엇인지에 대해 간략하게 적어주세요!
https://lionz12.netlify.app/homework 같은 출처 : 같은 프로토콜,도메인,포트를 사용하고 있습니다
https://lionz12.netlify.app/homework-submit/69 같은 출처: 같은 프로토콜,도메인,포트를 사용하고있습니다
http://lionz12.netlify.app/homework 다른 출처 : 다른 프로토콜을 사용하고 있습니다
https://lionz12.seminar.com 다른 출처 : 다른 도메인을 사용하고 있습니다

3.Access-Control-Allow-Origin : * 는 무슨 의미일지, 그리고 이렇게 설정한다면 무슨 일이 일어날지 생각해보세요!
-Access-Control-Allow-Origin 헤더를 사용하면 서버가 특정 출처 또는 모든 출처에 대해 자원 접근을 허용할 수 있습니다. 이때 *는 모든 출처를 의미하므로 어떤 요청이 오더라도 서버는 이를 허용하게 됩니다.
이따 악의적인 사이트가 서버 자원에 접근해 민감한 데이터를 훔치거나 악용하는 등 보안에 문제가 생길 수 있습니다.

4.CORS와 같이 어플리케이션에서 사용자 정보를 탈취하는 것을 막기 위한 정책인 CSRF(Cross-Site Request Forgery)가 무엇인지, django에서는 CSRF 공격을 어떻게 방어하는지도 알아보면 좋을 것 같아요

csrf는 웹 보안 공격 중 하나로, 악의적인 웹 사이트가 사용자의 브라우저를 이용하여 사용자가 의도하지 않은 요청을 다른 웹 사이트에 보내게 하는 공격입니다.

django에서 csrf공격을 방허하는 방법은 csrf 토큰을 사용하는 것입니다. 모든 POST, PUT, DELETE 요청에 대해 CSRF 토큰을 검증합니다. CSRF 토큰은 서버가 생성하여 클라이언트에게 전송하고, 클라이언트는 이 토큰을 후속 요청에 포함시킵니다. 서버는 요청이 들어올 때마다 이 토큰을 검증하여 요청이 신뢰할 수 있는 출처에서 왔는지 확인합니다.
![5-22 과제 제출](https://github.com/likelion-Inha-12/chanbro524/assets/164038275/6cb4873f-0d26-41fd-b873-12b7f96e7179)

**Comment by juwon0403** [comment]
정리와 캡처 사진까지 잘 제출해주셨습니당!!

csrf공격 방어하는 방법에는 토큰 사용 외에도 다양한 방법들이 있는데, 다른 아기사자들 레포 돌아보면서 참고하시면 더 도움이 되실 것 같아요!!

수고하셨서요~~~
