### ISSUE TITLE
백엔드 이찬형 7주차 배포 과제 제출합니다

### ISSUE THREAD

**Issue by chanbro0524** [likelion-Inha-12/chanbro524#8]
![배포1](https://github.com/likelion-Inha-12/chanbro524/assets/164038275/b82d799a-c59d-4101-8dba-814bcb0c4cd3)

![배포2](https://github.com/likelion-Inha-12/chanbro524/assets/164038275/c14562c2-7a10-46a0-9d11-1a7ee18c2fa6)

**Comment by juwon0403** [comment]
끝부분에서 살짝 오류가 있긴 했지만, 나머지 과정들을 너무 너무 잘하셨습니당
수고하셨어요!!!!
